version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: referencias_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Referencias
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: referencias_backend
    restart: always
    depends_on:
      - mysql
    environment:
      PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: Referencias
      JWT_SECRET: r3f3r3nc1as_app_s3cr3t_k3y_2024_xK9#mP2$nL
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: referencias_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "4321:4321"

volumes:
  mysql_data: